version: "3.9"
services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - "db"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/sin
      - SPRING_DATASOURCE_USERNAME=klaas
      - SPRING_DATASOURCE_PASSWORD=password
    links:
      - "db"
  db:
    image: "postgres:13.1-alpine"
    environment:
      - POSTGRES_USER=klaas
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=sin
    ports:
      - "5432:5432"
    volumes:
      - sinData:/var/lib/postgresql/data
      - ./src/main/resources/db/init.sql:/docker-entrypoint-initdb.d/init.sql

  nginx:
    build: frontend/
    restart: unless-stopped
    ports: 
    - "80:80"
    - "443:443"
    depends_on: 
      - "db"
      - "backend"
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/ssl:/usr/nginx
    links:
      - "backend"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"

volumes:
  sinData:
