CREATE TABLE accounts
(
    did  integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name varchar(40) NOT NULL,
    password varchar(40) NOT NULL,
    email varchar(150) NOT NULL
);

INSERT INTO accounts (name, password, email) VALUES ('admin', 'admin', 'admin@admin.de');
