DROP TABLE IF EXISTS accounts;
CREATE TABLE accounts
(
    did  integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username varchar(40) NOT NULL UNIQUE,
    password varchar(40) NOT NULL,
    email varchar(150) NOT NULL UNIQUE
);

INSERT INTO accounts (username, password, email) VALUES ('admin', 'admin', 'admin@admin.de');

<<<<<<< HEAD:backend/src/main/resources/db/init.sql
=======
DROP TABLE IF EXISTS numbers;
CREATE TABLE numbers
(
    did integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    number integer NOT NULL
);
>>>>>>> a72a34b28969962942b6b284f94e3c598a369d88:src/main/resources/db/init.sql

