DROP TABLE IF EXISTS accounts CASCADE;
CREATE TABLE accounts
(
    did      integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username varchar(40)  NOT NULL UNIQUE,
    password varchar(40)  NOT NULL,
    email    varchar(150) NOT NULL UNIQUE
);

INSERT INTO accounts (username, password, email)
VALUES ('admin', '21232F297A57A5A743894A0E4A801FC3', 'admin@admin.de');

DROP TABLE IF EXISTS numbers;
CREATE TABLE numbers
(
    did    integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    number integer NOT NULL
);

DROP TABLE IF EXISTS orders CASCADE;
CREATE TABLE orders
(
    did    integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    amount integer NOT NULL,
    good   text    NOT NULL,
    userId integer NOT NULL,
    CONSTRAINT fk_user
        FOREIGN KEY (userId)
            REFERENCES accounts (did)
);


grant all privileges on database sin to klaas;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO klaas;
